Repository TwinDragonLikesLatte/LattePanda, pull requests merged in 2022-02, with the labels that each got.

#47 [Comment](대시보드, 매장관리): Add Java Document 주석 추가
  src/main/java/com/test/main/home/AreaDailySellProdDTO.java
  src/main/java/com/test/main/home/AreaDalyAllTotalDTO.java
  src/main/java/com/test/main/home/AreaMonSellProdDTO.java
  src/main/java/com/test/main/home/AreaMontlyTotalDTO.java
  src/main/java/com/test/main/home/DailySellProdDTO.java
  src/main/java/com/test/main/home/DashBoard.java
  src/main/java/com/test/main/home/DashBoardDAO.java
  src/main/java/com/test/main/home/EmployeeScheduleDTO.java
  src/main/java/com/test/main/home/MontlyTotalDTO.java
  src/main/java/com/test/main/home/NoticeDTO.java
  src/main/java/com/test/main/home/StaffScheduleDTO.java
  src/main/java/com/test/main/home/StockRemainDTO.java
  src/main/java/com/test/main/store/NetProfit.java
  src/main/java/com/test/main/store/OperatingProfit.java
  src/main/java/com/test/main/store/ProfitValuesDTO.java
  src/main/java/com/test/main/store/StoreDAO.java
  src/main/java/com/test/main/store/StoreProfitDTO.java
Labels: 대시보드, 매장관리

#49 [Comment](대시보드): Add Java Document 주석 추가 수정
  src/main/java/com/test/main/home/DashBoardDAO.java
  src/main/java/com/test/main/store/OperatingProfit.java
  src/main/java/com/test/main/store/StoreDAO.java
Labels: 대시보드, 매장관리

#51 [Feat](Login): Add hashing SHA-256 on password
  src/main/java/com/test/main/login/Login.java
  src/main/java/com/test/main/login/SHA256.java
Labels: 로그인

#52 [Feat](Login): Add salting and key stretching on password
  src/main/java/com/test/main/login/Login.java
  src/main/java/com/test/main/login/LoginDAO.java
  src/main/java/com/test/main/login/SHA256.java
  src/main/java/com/test/main/login/SecurityDTO.java
Labels: 로그인

#53 [Feat](HR): Add access control based on servlet path
  src/main/java/com/test/main/access/AccessController.java
  src/main/java/com/test/main/home/DashBoard.java
  src/main/java/com/test/main/hr/employee/List.java
  src/main/java/com/test/main/hr/employee/add.java
  src/main/java/com/test/main/hr/staff/Attend.java
  src/main/java/com/test/main/hr/staff/List.java
  src/main/webapp/WEB-INF/inc/header.jsp
  src/main/webapp/WEB-INF/inc/sub-nav_hr.jsp
Labels: 인사관리
