Repository TwinDragonLikesLatte/LattePanda, pull requests merged in 2022-01, with the labels that each got.

#33 [Feat](메뉴관리): Add 메뉴조회, 판매제품조회, 상세조회, 메뉴등록 기능 구현
  src/main/java/com/test/main/menu/basic/Add.java
  src/main/java/com/test/main/menu/basic/AddOk.java
  src/main/java/com/test/main/menu/basic/AddOkProduct.java
  src/main/java/com/test/main/menu/basic/AddProduct.java
  src/main/java/com/test/main/menu/basic/CategoryDAO.java
  src/main/java/com/test/main/menu/basic/CategoryDTO.java
  src/main/java/com/test/main/menu/basic/Detail.java
  src/main/java/com/test/main/menu/basic/Edit.java
  src/main/java/com/test/main/menu/basic/EditOk.java
  src/main/java/com/test/main/menu/basic/EditOkProduct.java
  src/main/java/com/test/main/menu/basic/EditProduct.java
  src/main/java/com/test/main/menu/basic/List.java
  src/main/java/com/test/main/menu/basic/MenuDAO.java
  src/main/java/com/test/main/menu/basic/MenuDTO.java
  src/main/java/com/test/main/menu/basic/RecipeDAO.java
  src/main/java/com/test/main/menu/basic/RecipeDTO.java
  src/main/java/com/test/main/menu/basic/RegMenuDAO.java
  src/main/java/com/test/main/menu/basic/RegMenuDTO.java
  src/main/java/com/test/main/menu/product/List.java
  src/main/java/com/test/main/menu/product/ProductDAO.java
  src/main/java/com/test/main/menu/product/ProductDTO.java
  src/main/webapp/WEB-INF/inc/sub-nav_menu.jsp
  src/main/webapp/WEB-INF/views/menu/basic/add.jsp
  src/main/webapp/WEB-INF/views/menu/basic/addProduct.jsp
  src/main/webapp/WEB-INF/views/menu/basic/addok.jsp
  src/main/webapp/WEB-INF/views/menu/basic/detail.jsp
  src/main/webapp/WEB-INF/views/menu/basic/edit.jsp
  src/main/webapp/WEB-INF/views/menu/basic/editProduct.jsp
  src/main/webapp/WEB-INF/views/menu/basic/list.jsp
  src/main/webapp/WEB-INF/views/menu/product/list.jsp
  src/main/webapp/asset/css/menu/detail.css
  src/main/webapp/asset/css/menu/menu.css
  src/main/webapp/resources/images/AMC-H.jpg
  src/main/webapp/resources/images/AMC-I.jpg
  src/main/webapp/resources/images/LAT-H.jpg
  src/main/webapp/resources/images/LAT-I.jpg
  src/main/webapp/resources/images/VAT-H.jpg
  src/main/webapp/resources/images/VAT-I.jpg
Labels: 메뉴관리

#37 [Feat](HR): Add org-chart, staff-list, staff-attend / [Fix, Style](Login): Edit bug, style
  src/main/java/com/test/main/hr/department/DepartmentDAO.java
  src/main/java/com/test/main/hr/department/DepartmentDTO.java
  src/main/java/com/test/main/hr/department/OrgChartData.java
  src/main/java/com/test/main/hr/staff/Attend.java
  src/main/java/com/test/main/hr/staff/AttendDAO.java
  src/main/java/com/test/main/hr/staff/AttendDTO.java
  src/main/java/com/test/main/hr/staff/List.java
  src/main/java/com/test/main/hr/staff/StaffDAO.java
  src/main/java/com/test/main/hr/staff/StaffDTO.java
  src/main/java/com/test/main/login/Login.java
  src/main/java/com/test/main/login/LoginDAO.java
  src/main/webapp/WEB-INF/inc/org-chart.jsp
  src/main/webapp/WEB-INF/views/hr/staff/attend.jsp
  src/main/webapp/WEB-INF/views/hr/staff/list.jsp
  src/main/webapp/WEB-INF/views/login/changepw.jsp
  src/main/webapp/WEB-INF/views/login/changepwok.jsp
  src/main/webapp/WEB-INF/views/login/findpwid.jsp
  src/main/webapp/WEB-INF/views/login/findpwnamessn.jsp
  src/main/webapp/WEB-INF/views/login/login.jsp
  src/main/webapp/asset/css/findpassword.css
  src/main/webapp/asset/css/hr/staff/attend.css
  src/main/webapp/asset/css/hr/staff/list.css
  src/main/webapp/asset/css/login.css
Labels: bug, 인사관리, 로그인

#38 [Fix](Common): Edit sub-nav bug
  src/main/webapp/WEB-INF/inc/sub-nav_hr.jsp
  src/main/webapp/asset/js/sub-nav.js
Labels: bug, 공통

#42 [Feat](메뉴관리): Add 신규판매제품등록 기능 추가 기존 CSS 수정
  src/main/java/com/test/main/menu/basic/AddOkProduct.java
  src/main/java/com/test/main/menu/basic/AddProduct.java
  src/main/java/com/test/main/menu/basic/MenuDTO.java
  src/main/java/com/test/main/menu/basic/RecipeDAO.java
  src/main/java/com/test/main/menu/basic/RecipeDTO.java
  src/main/java/com/test/main/menu/basic/RegMenuDAO.java
  src/main/java/com/test/main/menu/basic/RegMenuDTO.java
  src/main/java/com/test/main/menu/basic/StockDAO.java
  src/main/java/com/test/main/menu/basic/StockDTO.java
  src/main/java/com/test/main/menu/product/ProductDAO.java
  src/main/java/com/test/main/menu/product/ProductDTO.java
  src/main/webapp/WEB-INF/inc/sub-nav_menu.jsp
  src/main/webapp/WEB-INF/views/menu/basic/add.jsp
  src/main/webapp/WEB-INF/views/menu/basic/addProduct.jsp
  src/main/webapp/WEB-INF/views/menu/basic/addproduct.jsp
  src/main/webapp/WEB-INF/views/menu/basic/detail.jsp
  src/main/webapp/WEB-INF/views/menu/basic/list.jsp
  src/main/webapp/WEB-INF/views/menu/product/list.jsp
  src/main/webapp/asset/css/menu/detail.css
  src/main/webapp/asset/css/menu/menu.css
Labels: 메뉴관리

#43 [Fix](All): Edit all views and function for presentation
  src/main/java/com/test/main/home/DashBoard.java
  src/main/java/com/test/main/hr/department/OrgChartData.java
  src/main/java/com/test/main/hr/employee/EmployeeDAO.java
  src/main/java/com/test/main/hr/employee/EmployeeDTO.java
  src/main/java/com/test/main/hr/employee/List.java
  src/main/java/com/test/main/hr/staff/Attend.java
  src/main/java/com/test/main/hr/staff/AttendDAO.java
  src/main/java/com/test/main/hr/staff/List.java
  src/main/java/com/test/main/hr/staff/Paystub.java
  src/main/java/com/test/main/hr/staff/PaystubDAO.java
  src/main/java/com/test/main/hr/staff/PaystubDTO.java
  src/main/java/com/test/main/login/Login.java
  src/main/java/com/test/main/login/LoginBtn.java
  src/main/java/com/test/main/login/LoginDAO.java
  src/main/java/com/test/main/login/LoginDTO.java
  src/main/java/com/test/main/stock/list/List.java
  src/main/webapp/WEB-INF/inc/header.jsp
  src/main/webapp/WEB-INF/inc/sub-nav_hr.jsp
  src/main/webapp/WEB-INF/views/home/dashboard.jsp
  src/main/webapp/WEB-INF/views/hr/employee/list.jsp
  src/main/webapp/WEB-INF/views/hr/staff/list.jsp
  src/main/webapp/WEB-INF/views/hr/staff/paystub.jsp
  src/main/webapp/WEB-INF/views/notice/board.jsp
  src/main/webapp/WEB-INF/views/notice/view.jsp
  src/main/webapp/WEB-INF/views/order/alllist.jsp
  src/main/webapp/WEB-INF/views/store/netprofit.jsp
  src/main/webapp/WEB-INF/views/store/operatingprofit.jsp
  src/main/webapp/asset/css/header.css
  src/main/webapp/asset/css/hr/employee/list.css
  src/main/webapp/asset/css/hr/staff/paystub.css
  src/main/webapp/asset/css/store/store.css
  src/main/webapp/index.jsp
Labels: bug, 공지, 주문관리, 대시보드, 인사관리, 로그인

#44 [Fix](HR): Edit paystub code sequence
  src/main/webapp/WEB-INF/views/hr/staff/paystub.jsp
Labels: 인사관리

#45 [Comment](메뉴관리): Add Java Document 주석 추가
  src/main/java/com/test/main/menu/basic/Add.java
  src/main/java/com/test/main/menu/basic/AddOk.java
  src/main/java/com/test/main/menu/basic/AddOkProduct.java
  src/main/java/com/test/main/menu/basic/AddProduct.java
  src/main/java/com/test/main/menu/basic/CategoryDAO.java
  src/main/java/com/test/main/menu/basic/CategoryDTO.java
  src/main/java/com/test/main/menu/basic/Detail.java
  src/main/java/com/test/main/menu/basic/List.java
  src/main/java/com/test/main/menu/basic/MenuDAO.java
  src/main/java/com/test/main/menu/basic/MenuDTO.java
  src/main/java/com/test/main/menu/basic/RecipeDAO.java
  src/main/java/com/test/main/menu/basic/RecipeDTO.java
  src/main/java/com/test/main/menu/basic/RegMenuDAO.java
  src/main/java/com/test/main/menu/basic/RegMenuDTO.java
  src/main/java/com/test/main/menu/basic/StockDAO.java
  src/main/java/com/test/main/menu/basic/StockDTO.java
  src/main/java/com/test/main/menu/product/List.java
  src/main/java/com/test/main/menu/product/ProductDAO.java
  src/main/java/com/test/main/menu/product/ProductDTO.java
Labels: 메뉴관리
